DOI-ONRR/nrrd

database/src/create.views.db.js
src/components/layouts/StateCard.js
src/components/sections/ExploreData/ExploreData.js

Fixes #4846
sunglasses [PREVIEW](https://4846-natinalrevenuecard.app.cloud.gov/explore/)
Adds national revenue card with minimize button.   Minimize button collapses card content but should also move card out of slot so  different state can make use of the real estate.  I'm going to allow that to be a different issue. .

4846 natinal revenue card

---

package-lock.json
package.json

- Upgraded Gatsby to latest build
-
-

upgraded gatsby

---

src/components/data-viz/StackedBarChart/StackedBarChart.js
src/components/data-viz/StackedBarChart/stacked-bar-chart.js
src/components/sections/TotalRevenue/TotalRevenue.js

Fixes #7
[:sunglasses: PREVIEW](https://7-revenuetabonclouddotgov.app.cloud.gov/)
- Adds legend styling
- Adds legend formatting

remove merge conflict

---

.circleci/preview.sh
manifest.staging.yml

[:sunglasses: PREVIEW](https://164-previewbug.app.cloud.gov/explore/)
Add logic to determine commit history and remove the oldest staged branch instead of one at randome
-
-
-

164 preview bug

---

src/pages/downloads/federal-production.mdx
src/pages/downloads/federal-revenue-by-location.mdx

[:sunglasses: PREVIEW](https://geothermalsulfur.app.cloud.gov/)
In Production downloads page:
Capitalizes sulfur in Geothermal - Sulfur to make it consistent
Changes commodity to Geothermal - Sulfur (tons)
-
-
-

Add tons to Geothermal - Sulfur

---

database/ddl/land_stats.sql

Fixes #196 
[:sunglasses: PREVIEW](https://hasura-onrr.app.cloud.gov/console/data/schema/public/tables/land_stats/browse)
added table land_stats to put federal land stats into database
-
-
-

Script to create federal owner ship table called land_stats

---

src/pages/downloads/index.mdx

Fixes #171 
[:sunglasses: PREVIEW](https://171-datavalidation.app.cloud.gov/downloads/)
- add data collection and validation to main download page
-
-

Adding data collection and validation info to download page

---

database/ddl/disbursment_source_summary.view.sql
src/components/sections/ExploreData/Disbursements/DisbursementRecipientSummary.js
src/components/sections/ExploreData/Disbursements/DisbursementRecipients.js
src/components/sections/ExploreData/Disbursements/DisbursementSources.js
src/components/sections/ExploreData/Disbursements/DisbursementTrend.js
src/pages/explore.mdx

Fixes #187 
[:sunglasses: PREVIEW](https://187-BuildDisbursmentCards.app.cloud.gov/explore/)
Changes proposed in this pull request: 
Added circle chart for disbursement by source
-
-
-

added DisbursmentSources component

---

src/components/data-viz/LineChart/D3LineChart.js
src/components/data-viz/LineChart/LineChart.js
src/components/sections/ExploreData/ExploreData.js
src/components/sections/ExploreData/RevenueOverTime.js

Fixes #177
[:sunglasses: PREVIEW](https://177-LineChart.app.cloud.gov/explore/)
Added a revenue over time line chart to explore data page
-
-
-

Got revenue over component in place

---

database/ddl/fiscal_production_summary.view.sql
src/components/sections/ExploreData/MapToolbar.js
src/components/sections/ExploreData/Production/ProductionMap.js

Fixes #69
[:sunglasses: PREVIEW](https://69-addproductionmap.app.cloud.gov/explore/)
-
-
-

Added fiscal production to clorapleth and wired up drop down

---

src/components/GlossaryTerm/GlossaryTerm.js
src/components/data-viz/CircleChart/D3CircleChart.js
src/components/data-viz/LineChart/D3LineChart.js
src/components/data-viz/Map/D3Map.js
src/components/data-viz/PieChart/D3PieChart.js
src/components/data-viz/StackedBarChart/D3StackedBarChart.js
src/components/data-viz/StackedBarChart/stacked-bar-chart.js
src/components/layouts/DefaultLayout/DefaultLayout.js
src/components/layouts/PageLayoutManager/PageLayoutManager.js
src/components/sections/DisbursementTrends/DisbursementTrends.js
src/components/sections/Explore/Disbursements.js
src/components/sections/Explore/Production.js
src/components/sections/Explore/Revenue.js
src/components/sections/ExploreData/AddCardButton.js
src/components/sections/ExploreData/AddLocationCard.js
src/components/sections/ExploreData/MapContext.js
src/components/sections/ExploreData/MapSelectControl.js
src/components/sections/ExploreData/MapToolbar.js
src/components/sections/ExploreData/YearSlider.js
src/components/sections/RevenueTrends/RevenueTrends.js
src/components/sections/TotalProduction/TotalProduction.js
src/components/sections/TotalRevenue/TotalRevenue.js
src/js/bar-charts/stacked-bar-chart.js
src/pages/explore.mdx
src/pages/index.mdx

Fixes #388, #418, #336, #334, #335, #378, #326, #327, #317, #319, #324
[:sunglasses: PREVIEW](https://311-accessibilitytestingandimprovements.app.cloud.gov/)
- Rename toolbar select "Offshore map"
- Remove color from surrounding counties 
- Remove "calendar year" from menu
- Add Fiscal year to selected year display
- Remove "monthly" from period menu
- Section titles
- Fix homepage broken links
- Add location labels
- Line chart yAxis label updates

Show stopper updates/fixes

---

src/components/data-viz/DataTable/Custom/AllTypeProvider.js
src/components/data-viz/DataTable/Custom/CustomTableCell.js
src/components/data-viz/DataTable/Custom/CustomTableFixedCell.js
src/components/data-viz/DataTable/Custom/CustomTableSummaryRowGroupRow.js
src/components/data-viz/DataTable/Custom/CustomTableSummaryRowItem.js
src/components/data-viz/DataTable/Custom/CustomTableSummaryRowTotalRow.js
src/components/data-viz/DataTable/DataTable.js
src/components/toolbars/data-filters/BaseDataFilterSelect/BaseDataFilterSelect.js
src/components/toolbars/data-filters/DataTypeToggle/DataTypeToggle.js
src/js/utils.js

Fixes #352
[:sunglasses: PREVIEW](https://352-format-numbers-query-tool.app.cloud.gov)
- 352, 351 353, 308, 342, 333
-
-

fixed bugs

---

src/components/sections/WhatsNew/WhatsNew.js
src/pages/about.mdx
src/pages/how-revenue-works/coal-excise-tax.mdx
src/pages/how-revenue-works/coal.mdx
src/pages/how-revenue-works/disbursements.mdx
src/pages/how-revenue-works/federal-laws.mdx
src/pages/how-revenue-works/federal-reforms.mdx
src/pages/how-revenue-works/gomesa.mdx
src/pages/how-revenue-works/hpf.mdx
src/pages/how-revenue-works/index.mdx
src/pages/how-revenue-works/minerals.mdx
src/pages/how-revenue-works/native-american-economic-impact.mdx
src/pages/how-revenue-works/native-american-ownership-governance.mdx
src/pages/how-revenue-works/native-american-production.mdx
src/pages/how-revenue-works/native-american-revenue.mdx
src/pages/how-revenue-works/offshore-oil-gas.mdx
src/pages/how-revenue-works/offshore-renewables.mdx
src/pages/how-revenue-works/onshore-oil-gas.mdx
src/pages/how-revenue-works/onshore-renewables.mdx
src/pages/how-revenue-works/ownership.mdx
src/pages/how-revenue-works/revenues.mdx

Fixes #367
[:sunglasses: PREVIEW](https://367-update-how-it-to-how-revenue.app.cloud.gov/about)
- changed links to how-revenue-works
- changed text to How Revenue Works
-

Updated links and text

---

src/pages/about.mdx
src/pages/downloads/disbursements-by-month.mdx

Fixes #366 
[:sunglasses: PREVIEW](https://update-disbursed-link.app.cloud.gov/about/)
- Update link in about to go to how revenue works - disbursements
-
-

update disbursed link in about

---

src/components/content-partials/Footer.mdx

Fixes #363 
[:sunglasses: PREVIEW](https://update-footer-links.app.cloud.gov/explore/)
- Updates footer links
-
-

update footer links

---

src/components/sections/ExploreData/Production/ProductionTopLocations.js
src/components/sections/ExploreData/Revenue/RevenueDetailCommodities.js
src/components/sections/ExploreData/Revenue/RevenueDetailTrends.js
src/components/sections/ExploreData/Revenue/RevenueDetailTypes.js

Fixes #515
[:sunglasses: PREVIEW](https://515-RevenueCountyData.app.cloud.gov/explore/)
Fixes issue with data being incorrect between state and county changes.
Steps to reproduce:
1) Select colorado
2) select county level map
3) select Gunnison county
4) select state level
5) remove Colorado
6) select state Colorado
No charts should have stale or wrong data. 
-
-
-

515 revenue county data

---

src/components/sections/ExploreData/Production/ProductionTopLocations.js

Fixes #512 
[:sunglasses: PREVIEW](https://512-CountyData.app.cloud.gov/explore/)
-
-
-

fixed production counyt rollup

---

src/components/ErrorBoundary.js

Fixes #535 
[:sunglasses: PREVIEW](https://update-error-page.app.cloud.gov/)
- Just updated the message to:
<h1>An error has occurred.</h1>
<a href='/'><p>Please click here to return to the home page.</p></a>
-
-

Updated error boundary message

---

src/components/content-partials/WhatsNew.mdx

- Changed date to June 4 in What's New
-
-

changed date

---

src/components/sections/ExploreData/Disbursements/DisbursementRecipientSummary.js
src/components/sections/ExploreData/Disbursements/DisbursementsSummary.js

Fixes #513
[:sunglasses: PREVIEW](https://513-countydisbursementcardsshownodisbursements.app.cloud.gov/explore)
- fixes county disbursement summary cards showing "no disbursements" when there are some disbursements
-
-

Update for "no disbursements" message

---

src/pages/how-revenue-works/gomesa.mdx

[:sunglasses: PREVIEW](https://update-GOMESA.app.cloud.gov/how-revenue-works/gomesa)
- Removed reference to clicking on states
- Updated GOMESA numbers to FY 2020
-

remove reference to clicking and updated GOMESA data

---

package-lock.json
src/components/sections/DisbursementTrends/DisbursementTrends.js
src/components/sections/RevenueTrends/RevenueTrends.js
src/components/seo.js

Fixes #377
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)
- Fixes issue were invalid date was showing in revenue trends and disbursement trends for Firefox and Safari
-
-

Update for invalid date across major browsers

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://release-changes-601.app.cloud.gov/explore/)
- increment version 
- updated what's new section

change release version 6.0.1

---

src/pages/how-revenue-works/native-american-revenue.mdx

Fixes #496 
[:sunglasses: PREVIEW](https://native-american-reference.app.cloud.gov/explore/)
- took out sentence about table and capitalized documentation

take out sentence about table

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://release-changes-602.app.cloud.gov/)
- update increment version
-

update version and what's new

---

src/components/content-partials/Header.mdx
src/components/inputs/SearchSite/SearchSite.js
src/components/inputs/SearchSite/index.js
src/components/navigation/MobileMenu/MobileMenu.js
src/components/search/SearchResults.js
src/components/utils/Search/index.js

Fixes #320 
[:sunglasses: PREVIEW](https://320-add-search.app.cloud.gov/)
- Added search in the header and mobile menu
-
-

added search

---

src/constants/data-filter-constants.js
src/js/query-manager/query-tool-data-table-queries.js

Fixes #665 
[:sunglasses: PREVIEW](https://665-combine-state-offshore.app.cloud.gov/)
- Combine state and offshore into 1 column
-
-

Combined state and offshore region

---

src/components/DataFilterProviderWrapper/DataFilterProviderWrapper.js
src/components/data-viz/DataTable/DataTable.js
src/components/inputs/BaseSelectInput/BaseSelectInput.js
src/components/inputs/withDataFilterContext.js
src/stores/data-filter-store/index.js
src/stores/data-filter-store/reducers.js
wrap-root-element.js

Fixes #664 
[:sunglasses: PREVIEW](https://664-update-drop-downs.app.cloud.gov/query-data?dataType=Disbursements)
- Drop downs update when Url Params are used
-
-

Drop downs update when Url Params are used

---

src/components/data-viz/Map/D3Map.js
src/components/data-viz/Map/Map.js
src/components/sections/ExploreData/Disbursements/DisbursementMap.js
src/components/sections/ExploreData/MapContext.js
src/components/sections/ExploreData/Production/ProductionMap.js
src/components/sections/ExploreData/Revenue/RevenueMap.js
src/components/sections/ExploreData/Revenue/RevenueNationalSummary.js
src/js/utils.js

Fixes #314, 625
[:sunglasses: PREVIEW](https://314-MapZoomIssues.app.cloud.gov/explore/)
After zooming with scroll, the button zooms in or out from that zoom rather then reseting the results.
Made legend customizable. 
-
-
-

Got zoom to set state for external map controls

---

src/components/data-viz/DataTable/DataTable.js
src/components/inputs/BaseSelectInput/BaseSelectInput.js
src/components/inputs/ClearAllFiltersBtn/ClearAllFiltersBtn.js
src/components/inputs/ClearAllFiltersBtn/index.js
src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js
src/stores/data-filter-store/actions.js
src/stores/data-filter-store/reducers.js

Fixes #641
[:sunglasses: PREVIEW](https://641-clear-all-query-tool.app.cloud.gov/query-data/)
- Added clear all button to clear the filters on the more filters tab
-
-

641 clear all query tool

---

src/components/sections/TotalDisbursements/TotalDisbursements.js
src/pages/explore.mdx

Fixes #772, #775
[:sunglasses: PREVIEW](https://772-sourcefilemonthlydisbursements.app.cloud.gov/)
- fixes source file link for monthly disbursements bar chart
- updates compare production link

Source file disbursement monthly link and compare production link updates

---

src/pages/how-revenue-works/onshore-renewables.mdx

Fixes #790 
[:sunglasses: PREVIEW](https://dive-in.app.cloud.gov/how-revenue-works/onshore-renewables)
- Corrects rate and learn more content on onshore renewables page

Fixes onshore renewable content

---

src/components/sections/ExploreData/CardTitle.js
src/components/sections/ExploreData/LocationName.js
src/components/sections/ExploreData/MapContext.js
src/components/sections/ExploreData/Revenue/RevenueDetailTrends.js
src/components/sections/ExploreData/Revenue/RevenueSummaryTrends.js

Fixes #750
[:sunglasses: PREVIEW](https://750-addstatenametocountywithnodata.app.cloud.gov/explore)
- adds state name to county cards with no data

Adds state name to county cards with no data

---

package-lock.json
package.json
src/components/inputs/SearchLocationsInput/SearchLocationsInput.js
src/components/sections/ExploreData/MapContext.js

Fixes #773
[:sunglasses: PREVIEW](https://773-cantaddoffshoreareas.app.cloud.gov/explore/)
- ability to add offshore areas from search input

Add offshore areas from search input

---

src/pages/how-revenue-works/coal.mdx
src/pages/how-revenue-works/disbursements.mdx
src/pages/how-revenue-works/federal-laws.mdx
src/pages/how-revenue-works/hpf.mdx
src/pages/how-revenue-works/minerals.mdx
src/pages/how-revenue-works/offshore-oil-gas.mdx
src/pages/how-revenue-works/offshore-renewables.mdx
src/pages/how-revenue-works/onshore-oil-gas.mdx
src/pages/how-revenue-works/onshore-renewables.mdx
src/pages/how-revenue-works/revenues.mdx

Fixes #793, #792, #795, #788, #789, #758, #794, #784, #787 
[:sunglasses: PREVIEW](https://broken-links.app.cloud.gov/how-revenue-works/)
- Fixes links to LWCF, HPF, and Native American overview
- Adds missing links to BLM website
- Fixes links to rate tables from dive in pages
- Adds an extra sentence to the Plan section that clarifies leases on federal acquired lands.
- Updates disbursements data link with link to query tool
- Fixes broken link to NOAA laws
- Fixes broken link to outer continental shelf pdf

Fixes broken links

---

src/components/sections/DisbursementTrends/DisbursementTrends.js
src/components/sections/ExploreData/Disbursements/DisbursementTrend.js
src/components/sections/RevenueTrends/RevenueTrends.js

Fixes #799
[:sunglasses: PREVIEW](https://799-sitenotrenderingie.app.cloud.gov/)
- fixes site not rendering in IE

Fixes site not rendering in IE

---

src/pages/how-revenue-works/federal-laws.mdx
src/pages/how-revenue-works/ownership.mdx

Fixes #776 and #781
[:sunglasses: PREVIEW](https://fix-submerged-lands-act-link.app.cloud.gov/explore/)
- updates state submerged link

updated submerged lands act

---

gatsby-node.js

Fixes #826
[:sunglasses: PREVIEW](https://826-createredirectslwcfandhpf.app.cloud.gov/)
- Adds redirects for LWECF and HPF pages

Add redirects for LWCF and HPF pages

---

src/pages/how-revenue-works/lwcf.mdx

Fixes #796
[:sunglasses: PREVIEW](https://american-battlefield-link.app.cloud.gov/how-revenue-works/lwcf/)
-updated American Battlefield grant link

updates American Battlefield link

---

src/pages/how-revenue-works/federal-laws.mdx

Fixes #780
[:sunglasses: PREVIEW](https://minerals-materials-act.app.cloud.gov//how-revenue-works/federal-laws/)
- updates minerals materials act link

updates minerals materials acts link

---

src/pages/how-revenue-works/federal-laws.mdx
src/pages/how-revenue-works/native-american-revenue.mdx

Fixes #783, #782, #786 
[:sunglasses: PREVIEW](https://marinelink.app.cloud.gov/how-revenue-works/federal-laws/)
- update marine mammals act link 
- updates fogrma on federal laws
- updates fogrma on native american revenues

update marine mammals act link

---

src/components/content-partials/Footer.mdx

Fixes #885 
[:sunglasses: PREVIEW](https://blog-link.app.cloud.gov/)
- updates blog link in footer
-
-

change blog link in footer

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://release-changes-611.app.cloud.gov/)
- increment version
-

Release changes 6.1.1

---

src/pages/how-revenue-works/gomesa.mdx

Partially Fixes #704 
still need links
[:sunglasses: PREVIEW](https://GOMESA-tables.app.cloud.gov/how-revenue-works/gomesa)
- added tables with states/counties to GOMESA page
-
-

Gomesa tables

---

src/pages/about.mdx

Fixes #368
[:sunglasses: PREVIEW](https://368-add-history-blurb.app.cloud.gov/about)
- Updated link to archive site
-
-

update link to archive

---

src/components/content-partials/Footer.mdx

Fixes #900
[:sunglasses: PREVIEW](https://900-footerreleasenoteslink.app.cloud.gov/)
- adds footer release notes link
-
-

add footer release link

---

src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js

Fixes #916
[:sunglasses: PREVIEW](https://916-filtered-fix.app.cloud.gov/query-data/)
- fixed spelling of filtered on download links in query tool toolbar
-
-

fixed spelling of filtered

---

src/js/query-manager/query-tool-data-table-queries.js

Fixes #903 
[:sunglasses: PREVIEW](https://903-add-state-to-county.app.cloud.gov/query-data)
- added state to county name in production table
- added county_name to hasura query_table view
-

added state to county name in production table

---

src/components/layouts/IconLinks/ExploreDataLink/ExploreDataLink.js
src/components/layouts/LocationLink/LocationLink.js

Fixes #846
[:sunglasses: PREVIEW](https://846-consitentlinkstyles.app.cloud.gov/)
- create consistent link styling
-
-

Consistent link styles

---

src/components/Link/Link.js
src/components/content-partials/InfoBanner.mdx
src/components/data-viz/StackedBarChart/D3StackedBarChart.js
src/components/data-viz/StackedBarChart/StackedBarChart.js
src/components/images/UsFlagImg.js
src/components/sections/SectionControls/SectionControls.js
src/components/sections/TotalProduction/TotalProduction.js
src/pages/how-revenue-works/index.mdx

Fixes #
[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/)
- fixes months running into each other on smaller viewports
- skips to every other year or month in smallest viewports
- style updates to xAxis labels
- fixes production monthly bar charts xAxis labels being cutoff
- update to make stacked bar charts responsive on resize

Homepage mobile chart updates

---

.circleci/config.yml
.circleci/stage.sh
__tests__/lighthouse.test.js

Fixes #
[:sunglasses: PREVIEW](https://BRANCH_NAME_HERE.app.cloud.gov/explore/)
- enable the preview-nrrd url script in circleci
-
-

Add staging build

---

.circleci/config.yml
.circleci/stage.sh
__tests__/lighthouse.test.js

This PR is used to kick off the builds on CircleCi. It does not need to be merged. We merge individual branches to dev.

Staging Pull Request. DO NOT MERGE

---

.circleci/config.yml
src/components/sections/ExploreData/Disbursements/DisbursementTopRecipients.js
src/components/sections/ExploreData/Disbursements/NationwideDisbursementSummary.js
src/components/sections/ExploreData/MapContext.js
src/components/sections/ExploreData/Production/ProductionLocationTotal.js
src/components/sections/ExploreData/Revenue/RevenueNationalSummary.js

Fixes #962
[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore)
- fixes production summary spacing issue

fix spacing issue in production total paragraph

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[preview](https://preview-nrrd.app.cloud.gov/)
changes made in this PR:
- increment version

Release changes 6.2.0

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://BRANCH_NAME_HERE.app.cloud.gov/explore/)
-
-
-

Staging DO NOT MERGE

---

src/components/inputs/Filters/FiscalYearFilter.js
src/components/inputs/Filters/PeriodFilter.js
src/components/inputs/index.js
src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js
src/constants/data-filter-constants.js
src/js/query-manager/data-filter-queries.js
src/js/query-manager/query-tool-queries.js
src/stores/data-filter-store/reducers.js

[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/)
-
-
-

fixed period and year selector

---

src/components/data-viz/LineChart/LineChart.js
src/components/sections/ExploreData/Disbursements/DisbursementsOverTime.js
src/components/sections/ExploreData/Production/ProductionOverTime.js
src/components/sections/ExploreData/Revenue/RevenueOverTime.js

Fixes #998
[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore/)
- fixes bug introduced with line chart color updates
-
-

Fix for line charts

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/)
- increment version
-

Release changes 6.2.1

---

src/components/inputs/SearchLocationsInput/SearchLocationsInput.js
src/components/sections/ExploreData/DetailCards.js
src/components/sections/ExploreData/MapContext.js
src/components/sections/ExploreData/SummaryCards.js
src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js
src/pages/explore.mdx

Fixes #646
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/646-LocationSearch/explore)
- Updates Compare label to "Add state or county"
- Remove "card" from labels
- Updates to Add location card

location search verbiage updates

---

src/components/data-viz/StackedBarChart/StackedBarChart.test.js

Fixes #1019 
StackedBarChart unit test runs
-
-
-

1019 stacked barchart unit test

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changes-6.2.2/)
- what's new
- version

Release changes v6.2.2

---

src/components/sections/ExploreData/Revenue/RevenueByCompany.js
src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js
src/constants/data-filter-constants.js
src/pages/downloads/federal-revenue-by-company.mdx
src/pages/downloads/federal-revenue-by-location.mdx
src/pages/downloads/index.mdx
src/pages/explore.mdx

Fixes #1039
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1039-ChangeRevenueByCompany/explore/)
- updates Revenue by company to Federal revenue by company
-
-

update Revenue by company to Federal revenue by company

---

src/components/Link/Link.js
src/components/navigation/MobileMenu/MobileMenu.js
src/components/toolbars/AppToolbar/AppToolbar.js

Fixes #1080
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1080-ImproveUsabilityMobileMenu/)
- Updates mobile menu to have close button
- Adds Link component to moible menu component to get currentPage indication
-

Improve usability of mobile menu

---

src/components/content-partials/Footer.mdx

Fixes #1056 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1056-remove-dl/)
- Remove download data link from footer
-
-

remove download link from footer

---

src/components/navigation/PageSubMenu/PageSubMenu.js
src/components/sections/ExploreData/Revenue/RevenueTopLocations.js
src/pages/explore.mdx

Fixes #1108
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1108-SubnavMissingItems/explore/)
- updates pageSubNav component to filter out 'Federal revenue by company' menu item when period is FY
- 
-

Fix sub nav missing items

---

src/components/content-partials/Footer.mdx
src/components/navigation/PageSubMenu/PageSubMenu.js
src/components/sections/ExploreData/Disbursements/NationwideDisbursementSummary.js
src/components/sections/ExploreData/ExploreMoreDataButton.js
src/components/sections/ExploreData/Revenue/RevenueNationalSummary.js
src/pages/explore.mdx

Fixes #1053
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1053-CompareAndNationwideSections/explore/)
- Relabels scroll down button
- changes top link to map
- groups nationwide summaries into their respective section

Clarify difference between compare and nationwide sections

---

src/components/data-viz/DataTable/Custom/CustomTableHeaderSortLabel.js
src/components/data-viz/DataTable/DataTable.js

Fixes #1057
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1057-VisualSortArrow/query-data/)
- Adds new component CustomTableHeaderSortLabel to manage sort label
- Update MUI icons
- Updated stylgin

Different visual for query data sort label

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.2.3/)
- what's new
-increment version

update whats new and version

---

src/pages/about.mdx

Fixes #1176
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/update-archive-link/about)
- update link to archive
-
-

update link to archive on about page

---

src/components/inputs/SearchLocationsInput/SearchLocationsInput.js

Fixes #1104
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1104-RemoveOffshoreForDisbursements/explore/)
- Removes offshore from search location input label 
- Removes offshore options from option list
-

Remove offshore for disbursements

---

src/components/data-viz/StackedBarChart/D3StackedBarChart.js
src/components/sections/TotalRevenue/TotalRevenue.js

Fixes #1147
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1134-FixHoverMonthlyBarCharts)
- fixes legend from displaying wrong month
- updates to D3 _legendHeaders function that handles legendHeader overload object
-

Fix hover on monthly bar charts

---

src/pages/how-revenue-works/hpf.mdx

Fixes #1235 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/HPF-update/how-revenue-works/hpf)
- content updates in HPF page
-
-

HPF content updates

---

src/pages/how-revenue-works/ownership.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Alaska-Natives-link/how-revenue-works/ownership)
- Fixes link to Alaska Native Corporations
-
-

Fix Alaska Native Corporations link

---

src/components/layouts/BackgroundLayouts/CoalBackground.js
src/components/layouts/BackgroundLayouts/MineralsBackground.js
src/components/layouts/BackgroundLayouts/OffshoreOilGasBackground.js
src/components/layouts/BackgroundLayouts/OffshoreRenewablesBackground.js
src/components/layouts/BackgroundLayouts/OnshoreOilGasBackground.js
src/components/layouts/BackgroundLayouts/OnshoreRenewablesBackground.js
src/components/navigation/PageTabs/PageTab.js

Fixes #1224
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/fix-background-images/how-revenue-works/)
- fix background images in the how it works section
- fixed tab navigation for onshore and offshore tabs
-

Fixed How it works revenue backgroudn images and tab navigation

---

src/components/data-viz/DataTable/Custom/CustomTableHeaderCell.js
src/components/data-viz/DataTable/Custom/CustomTableHeaderSortLabel.js
src/components/data-viz/DataTable/DataTable.js

Fixes #1217 #892
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1217-sort-arrows/query-data/)
- Fixed sort buttons
- Added sort for grouping and breakout columns
-

Fixed sort arrows and added for grouping and breakout

---

src/components/data-viz/DataTable/Custom/CustomTableCell.js
src/components/data-viz/DataTable/Custom/CustomTableSummaryRowItem.js

Fixes #679 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/679-round-query-tool/query-data)
- I round to Dollar Float vs Dollar int. 
-
-

added cents to query tool

---

package-lock.json
src/components/sections/ExploreData/Production/ProductionCountyMap.js

Fixes #1189
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1189-ProductionCountyMapScale/explore?dataType=Production&location=NF%2CCO%2COK&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2019)
Fixed scale of county maps.
-
-
-

fixed county map scale in production

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.2.5/)
- update version

update what's new and version

---

src/components/inputs/BaseSelectInput/BaseSelectInput.js
src/components/inputs/Filters/StateOffshoreFilter.js
src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js
src/js/query-manager/data-filter-queries.js

Fixes #1279 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1279-sort-loc-by-order)
- The State/Offshore name in revenue is sorted by location order not alphabetical
-
-

add sort by loc_order and remove dups

---

src/components/inputs/BaseSearchSelect/BaseSearchSelect.js

Fixes #1312 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1312-company-search-fix/)
- Can clear a selected Company from search box (federal revenue by company)
-
-

can clear option selected and update OnChange

---

src/components/data-viz/QueryToolTable/QueryToolTable.js
src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js
src/js/query-manager/data-filter-queries.js
src/js/query-manager/query-tool-queries.js

Fixes #1323 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1323-add-commodity-disbursements/)
- Added Commodity as a breakout for Monthly Data
-
-

Add commodity as a breakout for Monthly

---

src/components/data-viz/QueryToolTable/Custom/TotalProvider.js
src/components/data-viz/QueryToolTable/QueryToolTable.js

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1339-align-right-query-tool/)
- numbers align right
- Group by fix for Production data
-

1339 align right query tool and 1340 Group By fix for single product

---

__mock_queries__/__use_static_query_results__/GlossaryTermsQuery_results.json
src/components/GlossaryTerm/GlossaryTerm.js
src/components/GlossaryTerm/GlossaryTerm.test.js
src/components/data-viz/QueryToolTable/Custom/CustomTableCell.js

Fixes #91 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/91-glossary-in-query-tool)
- Added glossary term component to the library
-
-

added glossary term to query tool

---

src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.2.6/)

update date on release

---

src/pages/downloads/disbursements-by-month.mdx
src/pages/downloads/disbursements.mdx
src/pages/downloads/federal-revenue-by-company.mdx
src/pages/downloads/federal-revenue-by-location.mdx
src/pages/downloads/production-by-month.mdx
src/pages/downloads/production.mdx
src/pages/downloads/revenue-by-month.mdx

Fixes #707
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/update-downloads-spacing/)
- Add line breaks to the fields and definitions section for the various downloads pages.
- Fixed a spacing issue in the production by month downloads page.
-

Fixed spacing issues for download pages

---

src/components/inputs/BaseToggle/BaseToggle.js
src/components/layouts/PageLayoutManager/PageLayoutManager.js
src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js
src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js
src/pages/explore.mdx
src/pages/how-revenue-works/aml-reclamation-program.mdx
src/pages/how-revenue-works/audits-and-assurances.mdx
src/pages/how-revenue-works/onshore-oil-gas.mdx
src/pages/index.mdx

Fixes #1252
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1252-QueryToolDownloadsGTM/query-data)
- adds data-dataType attr to download links
- this will allow GTM to pick up the attr to associate links with their respective dataType
-

add data-dataType attr to download links

---

src/pages/how-revenue-works/nppllrf.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/NPPLLRF-updates/how-revenue-works/nppllrf)
- Added 2021 projects
-
-

Nppllrf updates

---

src/components/data-viz/StackedBarChart/D3StackedBarChart.js
src/components/sections/ComparisonTable/ComparisonTable.js

Fixes #1377
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1377-ChartDataHover/)
- fixes issue with chart data not displaying properly on hover
-
-

Fix for issue with chart data hover

---

src/components/content-partials/Glossary.mdx
src/pages/downloads/production.mdx

Fixes #569
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/tickets-pounds/downloads/production/)
- Added tickets/pounds back to glossary
-  Added tickets/pounds question back to production download page
-

Tickets pounds

---

src/components/content-partials/Redirects.mdx

Fixes #1349
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1349-ArchiveWildCardRedirects/)
- add redirects for archive directories
-
-

add archive redirects

---

src/components/sections/ExploreData/Production/ProductionSummaryTrends.js
src/components/sections/ExploreData/YearSlider.js
src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js
src/stores/data-filter-store/reducers.js

Fixes #1371
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1371-YearSliderBug/explore)
- fix for year slider bug
-
-

Fix for year slider bug

---

src/pages/downloads/disbursements-by-month.mdx
src/pages/downloads/federal-revenue-by-company.mdx
src/pages/downloads/revenue.mdx

fixes fiscal year on revenue by month download page 
fixes any remaining oil and gas references to oil or gas 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/mdxfixes/)
-
-
-

updates oil and gas on download pages

---

src/pages/how-revenue-works/onshore-renewables.mdx

Fixes #1383
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1383-onshore-renewables/)
- Content updated based on the archive site
-
-

updated content for onshore renewables page

---

src/components/sections/ExploreData/MapContext.js
src/components/sections/ExploreData/MapLevel.js
src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1397-MakeCountyOffshoreMoreVisible/explore)
- Removes menu component that housed county and offshore controls
- Places controls directly to top left of map
- updates of styling to use HOC withStyles method

Make County/Offshore controls more visible

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Release-changes-v6.3.1) 
- update release version

update whats new and release version

---

src/components/data-viz/ProductionLastTwelveMonths/ProductionLastTwelveMonths.js
src/components/data-viz/RevenueLastTwelveMonths/RevenueLastTwelveMonths.js
src/pages/fact-sheet.mdx

- Updated fact sheet with lease
-
-

updated fact sheet to "lease"

---

src/pages/how-revenue-works/index.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/remove-legacy-fund/how-revenue-works)
- removed the info linking to the legacy information
-
-

comment out legacy fund paragraph

---

src/pages/how-revenue-works/disbursements.mdx

Fixes #1261
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/update-disbursements-page/how-revenue-works/disbursements)
- Made updates to the percentages that states receive
- Added spacing
- Added small paragraph for state and county level disbursements (GOMESA & geothermal)

Update disbursements page under how-revenue-works

---

src/pages/how-revenue-works/gomesa.mdx

Fixes #1447
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/GOMESA21/how-revenue-works/gomesa)
- Adds 2021 GOMESA numbers

Adds GOMESA 2021 numbers

---

src/components/content-partials/Footer.mdx

Fixes #1461
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1461-FooterLinksWrapping/)
- updates footer grid container to prevent wrapping in larger viewports
-
-

increase footer grid container

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.3.3) 
- update release version

Update what's new and version 

---

src/components/sections/TotalRevenue/TotalRevenue.js
src/components/toolbars/HomeDataFilters/HomeDataFilters.js
src/pages/index.mdx
src/stores/data-filter-store/reducers.js

Fixes #1470
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1470-HomepageLoadTime)
Improved Revenue load time
Todo
further improve revenue
Improve production and disbursement
-
-
-

Improved revenue tab load

---

src/components/data-viz/QueryToolTable/QueryToolTable.js

Fixes #1471 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/query-tool-enhancements/query-data)
- Added a better loading indicator
-
-

added better loading indicator for query tool

---

.circleci/config.yml
.env.dev
.env.prd
swap.sh

Fixes #1491
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1491-FixQueryTool-take2/)
No code change just built to review database changes to resolve query tool errors
-
-
-

1491 fix query tool take2

---

src/components/data-viz/QueryToolTable/Custom/CustomTableHeaderCell.js
src/components/data-viz/QueryToolTable/QueryToolTable.js

Fixes #1455 #1406 #1439
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1455-month-grouping/)
- Month is now part of the grouping
- Month is sorted by default
- Product is no longer a drop down

1455 month grouping

---

src/components/data-viz/QueryToolTable/QueryToolTable.js
src/components/sections/ExploreData/MapContext.js

Fixes #1483
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1483-MessageForFourCards/explore)
- adds message to explore data when more than four cards are selected
- adds mui snackbar components and handlers to explore data
-

Message for more than 4 cards

---

src/components/sections/ExploreData/Production/ProductionTopLocations.js

Fixes #1504 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1504-commasin-circle-charts)
- Added commas to the circle charts
-
-

added circleLabel with commas

---

database/ddl/total_revenue_summary.view.sql
database/manifest.yml
database/public/index.html
database/src/ELT/monthly_disbursement.load.sql
database/static/csv/disbursements/monthly_disbursements.csv

Fixes #1524 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/disbursement-monthly/)
- upload March disbursement

upload March data

---

src/components/GlossaryTerm/GlossaryTerm.js
src/components/GlossaryTerms/GlossaryTerms.js
src/components/layouts/Tabtastic/Tabtastic.js

Fixes #1401 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1401-tab-jump-fix)
- replaced navigate with javascript code that does not refresh the page
-
-

fix scroll to top on home page

---

src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js

Fixes #1580 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/fix-link/)
-

Fix query tool revenue download link

---

README.cloud.gov

Fixes #1568
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1568-BugDisbursmentQueryTool/)
No changes required.   I think something in new build (setting location to Federal offshore is correcting issue.   Sandbox doesn't seem to have problem.   hopefully next dev build will correct dev...
-
-
-

force rebuild of software to isolate bug in disbursements

---

README.cloud.gov
database/src/ELT/update_metadata.sql
manifest.yml

Fixes #1567
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1567-BetterOffshoreLabel/)
Federal offshore without region -> Not tied to a region
Federal onshore without a location -> Not tied to a location
Federal Onshore & Offshore    ->  Onshore & offshore
-
-
-

1567 better offshore label

---

src/stores/explore-data-store/reducers.js

Fixes #1621
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1621-AddNativeAmericanCardDefault/explore)
- Adds Native American card to initial explore data cards
-
-

add NA card to explore data store init state

---

src/pages/how-revenue-works/federal-laws.mdx

Fixes #1611
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/fogrma/how-revenue-works/federal-laws/)
- Adds FOGRMA 1996 amendments

Adds FOGRMA amendment

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.3.7/)
- Updated what's new
- Updated version
-

Release changesv6.3.7

---

src/components/content-partials/Glossary.mdx
src/components/layouts/Tabtastic/Tabtastic.js
src/components/sections/ExploreData/CardTitle.js
src/components/sections/ExploreData/YearSlider.js
src/components/sections/TotalRevenue/TotalRevenue.js
src/stores/data-filter-store/reducers.js

Fixes #1622
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1622-GlossariesDefaultCards/explore)
- Adds glossary terms and definitions for Nationwide Federal and Native American
- Adds GlossaryTerm component to detailCards title component
-

Define glossaries for default cards

---

src/components/content-partials/Glossary.mdx
src/pages/how-revenue-works/index.mdx

Fixes #1581 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Glossaries/)
Adding new glossaries to specific terms: Inspection Fees, Civil Penalties, Other Revenues
Adding new glossaries to specific terms: US Treasury, Historic Preservation Fund

Adding glossaries 

---

src/components/content-partials/Glossary.mdx

Fixes #1665 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/NewGlossaryTerms/)
Added in new glossary terms:

New Glossary Terms

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.3.8/)

Release changesv6.3.8

---

src/components/sections/ComparisonTable/ComparisonTable.js

Fixes #1403
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/comparison-text/)
- Adds line of text to homepage comparison indicating the current year is up to the current month we have available.

Updates comparison text.

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.3.9/)
- Updated version
- Updated what's new

Release changesv6.3.9

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release-changesv6.3.10/)
- Update version
- Update what's new

Release changesv6.3.10

---

database/src/ELT/monthly_disbursement.load.sql

Fixes #1760
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1760-USTreasuryAI/)
Fixed native american bug causing error on explore data page
-
-
-

fixed bug with monthly disbursement rollup of native american

---

src/components/content-partials/Glossary.mdx
src/pages/how-revenue-works/reclamation.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/content-updates/)
-fixes broken link in Reclamation page
-corrects spelling in Glossary

Links and Spelling

---

src/components/sections/TotalProduction/TotalProduction.js
src/components/toolbars/HomeDataFilters/HomeDataFilters.js

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Jan-22-data-uploads?/)
Added back fiscal year changes
-
-
-

Added back in changes

---

database/static/csv/disbursements/monthly_disbursements.csv

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Jan-22-Disbursements/)
- December 2021 Disbursements
-
-

Jan-22-Disbursements

---

database/static/csv/disbursements/monthly_disbursements.csv

Fixes #1976 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/monthly-data-upload/)
- January Disbursements

Update monthly data

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/6.6.6/)
- new blog post and what's new second try

update for version 6.6.6 take 2

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

updates what's new and agile blog
https://dev-nrrd.app.cloud.gov/

Dev to master 

---

database/static/csv/disbursements/monthly_disbursements.csv

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/August22Data/)
- added disbursements data 
-
-

disbursements

---

.env.dev

changed sandbox to dev in preview

---

src/pages/how-revenue-works/coal-excise-tax.mdx

Fixes #<2166>
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/coal-excise-2021/)
- Updated coal-excise-tax.mdx with 2021 information

Coal Excise Tax 2021

---

.circleci/config.yml
gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.6.9/)
-
-
-

Release6.6.9

---

.circleci/config.yml

Added debug to deploy

---

.circleci/config.yml
.env.dev

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/database/)
-
-
-

change database from sandbox to dev in .env.dev

---

.circleci/config.yml

remove  export CIRCLE_STAGE='nrrd-preview' &&

---

database/static/csv/disbursements/monthly_disbursements.csv
database/static/csv/revenue/September 2022 Revenue for Portal_CSV.csv

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Sept-22-Data/)
- Adds Sept 22 Revenue
-
-

Sept 22 Data

---

database/static/csv/disbursements/monthly_disbursements.csv

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.7.0/)
-
-
-

RI disbursements

---

database/README.md

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2262-revert-npm-deps)
- updated gatsby node js
- added "++" to get db to build
-

update gatsby node js  -  2262 revert npm deps

---

database/static/csv/disbursements/monthly_disbursements.csv
database/static/csv/revenue/September 2022 Revenue for Portal_CSV.csv
gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2022/)
- Adds September 2022 revenue data
- Adds September 2022 disbursements data
- Updates What's new & version

Fiscal Year Release 

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.7.2/)
-  Updated what's new section
-  Updated version to 6.7.2

updated what's new and version

---

.circleci/config.yml

Fixes complicated db switches and generating download files. 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/hasura-sandbox-interface/)
Change circleci to build prod database as it builds dev. 
-
-
-

Switched dev to point at dev.

---

.circleci/config.yml

Simplifies circleci config
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/hasura-sandbox-interface)
add logic that checks for database changes to three database jobs
-
-
-

Hasura sandbox interface

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/releasechangesv6.7.4/)
-
-
-

version and whats new

---

src/pages/how-revenue-works/gomesa.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/fix-gomesa-link/)
- At https://revenuedata.doi.gov/how-revenue-works/gomesa/, fixes the the Louisiana query data link

fix-gomesa-link

---

.circleci/config.yml

2266: Adds config.yml from Jan-23-data

---

.circleci/config.yml

Adds correct method for downloading and installing cf cli for dev and prod database builds.

Updates cf cli install for dev and prod

---

src/components/utils/PercentDifference/PercentDifference.js

Changes how percent difference is calculated to account for negative current and previous values.

2473: Updates percent difference calculation

---

.circleci/config.yml
database/src/ELT/calendar_year_production.load.sql
database/src/ELT/fiscal_year_production.load.sql
database/src/ELT/monthly_revenue.load.sh

Fixes #<2520>
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2520-fix-santa-barbara-spelling-explore-data/)
- Fix Santa Barbara spelling

2520 fix santa barbara spelling explore data

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.8.1/)
- What's new (updated date of release and list of what we're releasing)
- Update version to 6.8.1

update what's new and version 6.8.1

---

src/components/content-partials/Footer.mdx
src/pages/information-quality.mdx
src/pages/plain-language.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/new-footer-webpages/)
- Add Plain Language webpage to footer
- Add Information Quality webpage to footer

new-footer-webpages

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.8.3/)
- updated version to 6.8.3
- updated date and what's new items

pdate what's new and version 6.8.3

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.8.4/)
- What's New
- Version
-

update what's new and version 6.8.4

---

src/components/toolbars/AppToolbar/AppToolbar.js

2528-add-link-to-homepage-logo: Adds aria-label

---

.env.dev
database/ddl/query_tool_production.mview.sql

Fixes #2778
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2778-exclude-mixed-exploratory/)
- Updates materialized view to exclude mixed exploratory

2778 exclude mixed exploratory

---

database/ddl/production_commodity_options.view.sql

Fixes #2529 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2529-remove-coal-tons-from-commodity-filter/)
- Removes Coal (tons) from explore data Production options

2529-remove-coal-tons-from-commodity-filter: Updates options view.

---

src/components/data-viz/DisbursementsLastTwelveMonths/DisbursementsLastTwelveMonths.js
src/components/data-viz/Map/D3Map.js
src/components/data-viz/StackedBarChart/D3StackedBarChart.js
src/components/data-viz/StackedBarChart/HorizontalStackedBarChart.js
src/components/data-viz/StackedBarChart/StackedBarChart.js
src/components/data-viz/svg/Bars.js
src/components/images/index.js
src/components/sections/TotalDisbursements/TotalDisbursements.js
src/components/sections/TotalProduction/TotalProduction.js
src/components/sections/TotalRevenue/TotalRevenue.js
src/components/toolbars/AppToolbar/AppToolbar.js

Fixes #2708
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2708-fix-failing-audit-job-nrrd/)
- Fixes eslint warnings and error

2708-fix-failing-audit-job: Fixes eslint warnings

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.8.7/)
- what's new
- update version

update whats new and version 6.8.7

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/release6.8.8/)
- update version to 6.8.8

update what's new and version 6.8.8

---

gatsby-config.js
package-lock.json
package.json
src/components/seo.js

Fixes #2885
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2885-fix-dap-code-errors/)
- Update DAP type property
- Remove Gatsby plugin

2885 fix dap code errors

---

database/changelog/changelog-data/revenue-true-up.yaml
database/changelog/changelog-procedures/delete-revenue-create.yaml
database/changelog/src/procedures/delete_revenue.sql

Fixes #2888
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2888-revenue-true-up/)
- Adds Liquibase changelog YAML for revenue true-up process

Revenue true-up

---

database/changelog/changelog-data/revenue-true-up.yaml
database/changelog/changelog-functions/location-functions.yaml
database/changelog/changelog-triggers/location-triggers.yaml
database/changelog/src/functions/location_bri.sql
database/changelog/src/procedures/load_disbursement_monthly.sql
database/changelog/src/triggers/location_bri.sql

Fixes #2898
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/fyuploads/)
- Adds new trigger function for before insert on location
- Fixes stored logic of monthly disbursement load procedure

Additional changes needed for FY15 disbursements data

---

database/changelog/changelog-anonymous/fix-revenue-by-company-commodity.yaml
database/changelog/changelog-data/revenue-by-company.yaml
database/changelog/changelog-functions/revenue-by-company-functions.yaml
database/changelog/changelog-root.yaml
database/changelog/changelog-triggers/revenue-by-company-triggers.yaml
database/changelog/changelog-views/revenue-by-company-views.yaml
database/changelog/src/functions/revenue_by_company_bri.sql
database/changelog/src/triggers/federal_revenue_by_company_bri.sql
database/changelog/src/views/query_tool_revenue_by_company.sql

Fixes #2887
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2887-revenue-by-company/)
- Refactors data upload process
- Address commodity value issues ("N/a", "Oil & gas (pre-production)")
- Adds Liquibase changelog file for loading `federal_revenue_by_company`

Refactor revenue by company

---

.circleci/config.yml
database/src/scripts/downloads.sh
src/pages/downloads/federal-revenue-by-company.mdx

Fixes #1826
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1826-rbc-download-columns/)
- Changes column names in RBC download file
- Updates data dictionary to reflect name changes
- Updates CircleCI config.yml to add ability to manually trigger download generation

Update Revenue by company download column names

---

src/components/content-partials/Glossary.mdx

Fixes #2977 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/GlossaryUpdate/)
- Land Category: Distinguishes between data collected onshore and offshore within NRRD datasets.
- Land Class: Distinguishes federal lands and waters from Native American lands within NRRD datasets.
- Land Type: Combines land class and land category within NRRD's Query Data tool.
- Offshore: Submerged lands located farther than three miles off a state’s coastline, or three marine leagues into the Gulf of Mexico off Texas and western Florida.
- Onshore: Situated or occurring on land.

GlossaryUpdate

---

.circleci/config.yml
.env.dev
.env.prd
gatsby-config.js
package-lock.json
package.json
src/components/seo.js

Fixes #3110
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/implement-gtm/)
- Implements Google Tag Manager

Implement gtm

---

src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Release6.8.12/)
- What's new 
- Updated version to 6.8.12

updated whats new and version 6.8.12

---

src/components/data-viz/QueryToolTable/QueryToolTableSales/SalesTableBase.js
src/components/data-viz/QueryToolTable/QueryToolTableSales/plugins/HeaderRowCell.js
src/components/sections/ExploreData/ExploreMoreDataButton.js

Fixes #3113
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/3113-explore-data-button-size/explore)
- Reduces size of map button

3113 explore data button size

---

database/changelog/changelog-data/disbursement.yaml
database/static/csv/disbursements/monthly_disbursements.csv

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/januarydisbursements/)
-
-
-

Add feb disbursements 

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/WhatsNew3-15/)
- updated What's New box
- updated version to 7.2.0: https://github.com/DOI-ONRR/nrrd/releases

WhatsNew3-15

---

static/googlea80a448341cf4a74.html

Addresses #3080 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/google-search-console/)
- Added html file from google search console to the static folder
-
-

Added google search console verification file

---

src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/WhatsNew3-29)
- updates what's new box

Update What's New 

---

src/pages/404.mdx
src/pages/downloads/federal-sales.mdx

Fixes #3220 - adds definition for unit value
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/federal-sales-DD-terminologyupdate/)

Update Federal Sales Data Download Data Dictionary Section

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/april24whatsnew/)
-Whats new box
-version 7.4.0
-

April 17 what's new and version

---

src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/April24factsheetchanges/)
FY21 & 22 fact sheet links in whats new
-
-
-

changed fact sheet tab link to two PDF links

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

@lpgoldstein please review:
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/WhatsNewJuly24/)

WhatsNewJuly24

---

static/onrr-data.json

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/add-json/)
-Fixes Landing page description
-
-

updated landing page description

---

static/onrr-data.json

fixes landing page description in onrr-data.json file
https://dev-nrrd.app.cloud.gov/onrr-data.json
Changed
"@type": "dcat:Distribution",
"description": "Landing page for statistics.",
to
"@type": "dcat:Distribution",
"description": "Landing page for disbursements data",

Dev > Master Update metadata json file

---

static/onrr-data.json

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/add-json/)
-
-
-

fix location spelling

---

static/onrr-data.json

Fixes location spelling in onnr-data.json file
[dev-nrrd.app.cloud.gov/onrr-data.json](https://dev-nrrd.app.cloud.gov/onrr-data.json)
-
-
-

Dev > Master onrr-data.json

---

static/onrr-data.json

Header changes based on contractor review
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/add-json/)
-
-
-

onrr-data.json file changes to collection header

---

static/onrr-data.json

[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/onrr-data.json)
- Updated header based on review by EDI contractors
-
-

Dev > Master updates to onrr-data.json

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew/)
- Update version 7.8.0 
- what's new

Update version 7.8.0 and what's new

---

static/onrr-data.json

Adds updated json file for metadata.

Update json file for data.gov metadata

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/)
- updates what's new
-
-

Whatsnew781

---

static/onrr-data.json

Add CY production to onrr-data.json

---

gatsby-config.js
src/pages/index.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/fact-sheet-tab/)

fact-sheet-tab

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whats-new-v7.10.0/)

Whats new v7.10.0

---

src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/RemoveWhatsNew/)

RemoveWhatsNew

---

database/changelog/changelog-anonymous/insert-fips-counties-exceptions-initial.yaml
database/changelog/changelog-tables/fips-counties-exceptions.yaml
database/changelog/changelog-views/explore-data-locations-view.yaml
database/changelog/changelog-views/revenue-summary-view.yaml
database/changelog/src/views/explore_data_locations_v.sql
database/changelog/src/views/revenue_summary_v.sql
src/components/inputs/SearchLocationsInput/SearchLocationsInput.js
src/components/sections/ExploreData/DetailCards.js
src/components/sections/ExploreData/MapContext.js

Fixes #2270 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2270-alaska-county-bug/explore)
- Fixes cards for fips codes having multiple counties/boroughs

Fixes data issues for Alaska boroughs in explore data

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew711/)
- update what's new date
- update version to 7.11.0

Whatsnew711

---

database/changelog/changelog-views/fiscal-year-disbursements-by-recipient.yaml
database/changelog/changelog-views/max-fy-period-view.yaml
database/changelog/src/views/fiscal_year_disbursements_by_recipient_v.sql
database/changelog/src/views/max_fy_period_v.sql
src/apollo/client.js
src/components/FactSheet/DisbursementsFactSheet.js
src/components/FactSheet/DisbursementsPieChart.js
src/components/FactSheet/FactSheetBanner.js
src/components/FactSheet/FactSheetFooter.js
src/components/FactSheet/ProductionFactSheet.js
src/components/FactSheet/RevenueFactSheet.js
src/components/FactSheet/index.js
src/components/data-viz/ChartTitle/ChartTitle.js
src/components/data-viz/ProductionLastTwelveMonths/ProductionLastTwelveMonths.js
src/components/data-viz/ProductionLastTwelveMonths/index.js
src/components/data-viz/RevenueLastTwelveMonths/RevenueLastTwelveMonths.js
src/components/data-viz/RevenueLastTwelveMonths/index.js
src/components/data-viz/StackedBarChart/D3StackedBarChart.js
src/components/info/SnapshotBanner/SnapshotBanner.js
src/components/info/SnapshotBanner/index.js
src/components/layouts/DefaultLayout/DefaultLayout.js
src/components/sections/ExploreData/Production/ProductionLandCategory.js
src/components/sections/ExploreData/Revenue/RevenueDetailCommodities.js
src/components/sections/ExploreData/Revenue/RevenueDetailTypes.js
src/components/sections/TotalRevenue/TotalRevenue.js
src/pages/fact-sheet.mdx

Fixes #3708 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/factsheet-updates/)

Factsheet updates

---

gatsby-config.js
src/pages/accessibility.mdx

https://dev-nrrd.app.cloud.gov/

dev -- master v7.12.1

---

.circleci/config.yml
src/components/content-partials/Glossary.mdx
src/pages/downloads/disbursements-by-month.mdx
src/pages/downloads/disbursements.mdx
src/pages/downloads/federal-sales.mdx
src/pages/downloads/production-by-disposition.mdx
src/pages/downloads/production-by-month.mdx
src/pages/downloads/production.mdx
src/pages/downloads/revenue.mdx
src/pages/explore/offshore-regions/gulf.mdx
src/pages/how-revenue-works/disbursements.mdx
src/pages/how-revenue-works/federal-laws.mdx
src/pages/how-revenue-works/federal-reforms.mdx
src/pages/how-revenue-works/gomesa.mdx
src/pages/how-revenue-works/index.mdx
src/pages/how-revenue-works/lwcf.mdx
src/pages/how-revenue-works/offshore-oil-gas.mdx
src/pages/how-revenue-works/ownership.mdx
src/pages/how-revenue-works/revenues.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Gulf-Updates/)

Gulf-Updates

---

database/changelog/changelog-anonymous/update-sales-offshore.yaml
src/pages/accessibility.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Feb-25-Uploads-Part2/)
- Updates to accessibility statement
- Updates to offshore region names within federal sales data
-

Feb-25-Uploads-Part2

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnewv7140/)

Whatsnewv7140

---

static/onrr-data.json

add new onrr-data.json

---

src/pages/accessibility.mdx
src/pages/downloads/federal-revenue-by-company.mdx
src/pages/downloads/production-by-disposition.mdx
src/pages/downloads/production-by-month.mdx
src/pages/how-revenue-works/federal-laws.mdx
src/pages/how-revenue-works/federal-reforms.mdx
src/pages/how-revenue-works/native-american-ownership-governance.mdx
src/pages/how-revenue-works/native-american-production.mdx
src/pages/vdp.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Content-Updates-March25/)
- #3819 Add crosswalk explainer to Fed Rev by Company
- #3810 Fix OGOR-B table
- #3828 Webpages with spacing issues
- #3843 Add Royalty Resiliency Act to Federal Laws page
Webpages to review:

Content-Updates-March25

---

src/pages/how-revenue-works/gomesa.mdx

- update Texas st number on GOA OCS page
-
-

Error fix dev --> master pr

---

src/pages/downloads/production-by-disposition.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/disposition-tables/)
- https://nrrd-preview.app.cloud.gov/sites/disposition-tables/downloads/production-by-disposition/

disposition-tables

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew/)
- Update what's new v8.5.0
- Update what's new with monthly data updates

Update whats new and version 8.5.0

---

gatsby-config.js
src/components/content-partials/WhatsNew.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew860/)
- update whats new
- update verson 8.6.0

Update version and whats new

---

src/pages/downloads/disbursements-by-month.mdx
src/pages/downloads/disbursements.mdx
src/pages/downloads/federal-revenue-by-company.mdx
src/pages/downloads/federal-sales.mdx
src/pages/downloads/production-by-disposition.mdx
src/pages/downloads/production-by-month.mdx
src/pages/downloads/production.mdx
src/pages/downloads/revenue.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/download-data-pages-update/)

download-data-pages-update

---

src/components/FactSheet/DisbursementsPieChart.js

Fixes #4038
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/4038-add-commas-to-numbers-in-disbursements/fact-sheet/)
- Updates number format on disbursements chart on Fact sheet

Fixes disbursements graph number format

---

database/changelog/changelog-anonymous/add-indexes-revenue-disbursements-period-id.yaml
gatsby-config.js
src/components/sections/ReleaseDetails/ReleaseDetails.js

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/what's-new-performance-tuning/)
- Adds database indexes
- Updates release details section

Adds index changelog; updates release details section

---

gatsby-config.js
src/pages/index.mdx

Fixes #4061
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/4061-landing-page-errors-on-mobile/)
- Removes old duplicative What's New block that is rendered only for small screens

Fixes home page error in mobile

---

gatsby-config.js
src/components/sections/ReleaseDetails/ReleaseDetails.js
src/pages/how-revenue-works/gomesa.mdx

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/gomesa-page-update/)

gomesa-page-updates

---

gatsby-config.js
src/components/FactSheet/FactSheetBanner.js
src/components/sections/ReleaseDetails/ReleaseDetails.js

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew8120/)
- Update release version v8.12.0
- fact sheet date August 
- latest release details

Update latest release v8.12.0

---

static/onrr-data.json

- Added new onrr-data.json to dev
-
-

Add updated json

---

gatsby-config.js
src/components/FactSheet/FactSheetBanner.js
src/components/sections/ReleaseDetails/ReleaseDetails.js

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/whatsnew8130/)
- Update fact sheet date
- Update what's new 8.13.0
- Update release date and add coal excise tax

Whatsnew8130
