src/components/sections/ExploreData/Production/ProductionTopLocations.js
Fixes #514 
[:sunglasses: PREVIEW](https://514-Otherproduction.app.cloud.gov/explore/)
State cards were fixed but other for national and native were still summing other top locations incorrectly
-
-
-
=> Fixed other production top locations at national level

src/apollo/client.js, src/js/data-filter-query-manager/production-queries.js, src/js/data-filter-query-manager/revenue-queries.js
Fixes #346 
[:sunglasses: PREVIEW](https://346-highest-value-commodites-first.app.cloud.gov/query-data)
- Order of commodities is according tp the commodity order
-
-
=> added commodity order to queries

src/components/data-viz/DataTable/DataTableGroupingToolbar/DataTableGroupingToolbar.js
Fixes #359 
[:sunglasses: PREVIEW](https://359-default-breakout-none.app.cloud.gov/query-data)
- Breakout is defaulted to none vs first non-group by value
-
-
=> default breakout to none

src/components/data-viz/DataTable/DataTable.js
Fixes #362 
[:sunglasses: PREVIEW](https://362-column-group-by.app.cloud.gov/query-data)
- The group by is now showing as a column 
-
-
=> added group by column

package-lock.json, src/pages/about.mdx, src/pages/how-revenue-works/aml-reclamation-program.mdx, src/pages/how-revenue-works/gomesa.mdx, src/pages/how-revenue-works/revenues.mdx
Fixes #497, #499, #500, #501
[:sunglasses: PREVIEW](https://fix-links.app.cloud.gov/explore/)
Fixes links:
- LWCF link on GOMESA page
- UMWA link on AML page
- Disbursements link on Revenues page
- Two links on About page
- Removes state links on GOMESA page (temporary fix for #494)
=> Fixes broken links

src/components/sections/ExploreData/Production/ProductionTopLocations.js
Fixes #586 
[:sunglasses: PREVIEW](https://586-NoDataError.app.cloud.gov/explore/)
Fixed issue where state with no data is selected in production data. 
-
-
-
=> Fixed Prodution top locations from erroring out if state had no data

src/pages/how-revenue-works/revenues.mdx
Fixes #415 
[:sunglasses: PREVIEW](https://revenuetable.app.cloud.gov/how-revenue-works/revenues)
- Rename headings to "Secure Lease or Claim, Before production, and During Production"
- Combine rents & fees together under the Before production phase
=> Revenue table: change to old headings and combine rents&fee

src/components/data-viz/DataTable/DataTable.js
Fixes #678 
[:sunglasses: PREVIEW](https://678-fix-downloads.app.cloud.gov/query-data)
- Download columns now will match what is selected
-
-
=> Fix Download Query Data

src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js
Fixes #725
[:sunglasses: PREVIEW](https://725-remove-county-filter.app.cloud.gov/query-data/)
- Removed the option to filter by county on revenue and production
-
-
=> removed county filter

src/components/toolbars/QueryTableToolbar/QueryTableToolbar.js, src/constants/data-filter-constants.js, src/js/data-filter-query-manager/disbursement-queries.js, src/js/query-manager/index.js, src/js/query-manager/query-tool-data-table-queries.js
Fixes #718
[:sunglasses: PREVIEW](https://718-disbursements-update.app.cloud.gov/query-data?dataType=Disbursements)
- Remove CY option, since we only have FY data
- Change "County" recipient to "State and local governments"
- Change "State/offshore region" label to just "State", since there are no disbursements to offshore regions
- Drops the ability to filter by county
- Only allow selecting or grouping by a state if you pick state and local governments recipient
- Change "county" to "local recipient" as a column available for grouping that includes the state and county level
- Pull GOMESA out of recipient names and have it as just a source
-
=> made changes to filters/grouping/values for disbursements query tool

src/components/data-viz/DataTable/DataTable.js
Fixes #809
[:sunglasses: PREVIEW](809-disbursements-col-cutoff-fix.app.cloud.gov)
- Default width is wider for recipient on query tool disbursements
-
-
=> bigger default width for Recipient

src/components/sections/ExploreData/Production/ProductionTopLocations.js, src/components/sections/ExploreData/Revenue/RevenueTopLocations.js
Fixes #801 
[:sunglasses: PREVIEW](https://801-WrongOrderTopLocations.app.cloud.gov/explore/)
Fixes the order of top locations - introduced when commodities were reflected as detail commodities are summed in client so the order was for the top commodities not the top state.   Sort after data is summarized
-
-
-
=> Fixed order of top locations array

src/pages/how-revenue-works/native-american-production.mdx, src/pages/how-revenue-works/native-american-revenue.mdx
Fixes #684
[:sunglasses: PREVIEW](https://query-links.app.cloud.gov/how-revenue-works/native-american-production/)
- Adds &landType=Native%20American param to the urls from Native American production and revenue pages that link to query tool
=> Adds land type parameter to urls

src/components/sections/ExploreData/Disbursements/NationwideDisbursementSummary.js, src/components/sections/ExploreData/Revenue/RevenueTopLocations.js, src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js
Fixes #855
[:sunglasses: PREVIEW](https://855-CommodityFilters.app.cloud.gov/explore/)
Fixed commodity drop down to only include commodities with revenue 
-
-
-
=> Fixed Production and Commoidty drop down lists

src/components/sections/ExploreData/Revenue/RevenueSummaryTrends.js
Fixes #866 
[:sunglasses: PREVIEW](https://866-DataIssueSummaryTrend.app.cloud.gov/explore/)
Fixed 0 issue in Revenue for timeseries with exactly 1 value. 
-
-
-
=> Fixed bad logic array length > 1 instead of > 0

src/components/data-viz/StackedBarChart/D3StackedBarChart.js, src/components/sections/ExploreData/DetailCards.js, src/components/sections/ExploreData/MapContext.js, src/components/sections/ExploreData/Revenue/RevenueDetailCommodities.js, src/components/sections/TotalProduction/TotalProduction.js
Fixes #957
[:sunglasses: PREVIEW](https://957-duplicatedatacards.app.cloud.gov/explore/)
- updates to RDC dataKey
- remove unshift of NF card from cards array
-
=> Fix for duplicate data in detail cards

src/components/data-viz/CircleChart/CircleChart.js, src/components/data-viz/LineChart/LineChart.js, src/components/navigation/PageToc/PageToc.js, src/components/sections/ExploreData/AddLocationCard.js, src/components/sections/ExploreData/DetailCards.js, src/components/sections/ExploreData/Disbursements/DisbursementRecipients.js, src/components/sections/ExploreData/Disbursements/DisbursementSources.js, src/components/sections/ExploreData/Disbursements/DisbursementTopRecipients.js, src/components/sections/ExploreData/Disbursements/DisbursementsOverTime.js, src/components/sections/ExploreData/MapContext.js, src/components/sections/ExploreData/Production/ProductionCountyMap.js, src/components/sections/ExploreData/Production/ProductionLandCategory.js, src/components/sections/ExploreData/Production/ProductionOverTime.js, src/components/sections/ExploreData/Production/ProductionTopLocations.js, src/components/sections/ExploreData/Revenue/RevenueCountyMap.js, src/components/sections/ExploreData/Revenue/RevenueDetailCommodities.js, src/components/sections/ExploreData/Revenue/RevenueDetailTypes.js, src/components/sections/ExploreData/Revenue/RevenueOverTime.js, src/components/sections/ExploreData/Revenue/RevenueTopLocations.js, src/components/sections/ExploreData/SummaryCards.js, src/components/utils/PercentDifference/PercentDifference.js, src/js/mui/palette.js, src/pages/how-revenue-works/index.mdx
Fixes #329
[:sunglasses: PREVIEW](https://preview-nrrd.app.cloud.gov/explore?dataType=Revenue&location=NF%2CNA%2CMT%2CCA&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2019)
- adds color to card headers to match line chart
-
-
=> Color card headers

src/components/sections/ExploreData/Disbursements/DisbursementLocationTotal.js
Fixes #1010 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1010-add-space/explore/?dataType=Disbursements&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2019)
- added space in disbursements summary sentence on explore data
-
-
=> add space in explore data disbursements summary

src/components/data-viz/LineChart/D3LineChart.js, src/components/sections/ExploreData/Disbursements/DisbursementLocationTotal.js, src/components/sections/ExploreData/MapContext.js, src/components/sections/ExploreData/Revenue/RevenueLocationTotal.js, src/components/sections/ExploreData/YearSlider.js, src/stores/data-filter-store/reducers.js
Fixes #1087, #1088
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2020-FixYearSliderRevenueAndProduction/explore/)
- fixes year slider for revenue and production 
- fixes for trendline tooltip not showing all years
-
=> fix to year slider max years, update line chart to get chart data years 

src/stores/explore-data-store/reducers.js
Fixes #1047
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1047-OpenNFCardByDefault/explore/)
- Sets nationwide federal card as default
-
-
=> Have nationwide card open by default

src/components/sections/ExploreData/ExploreMoreDataButton.js, src/components/sections/ExploreData/MapContext.js, src/components/sections/ExploreData/MapControls.js, src/components/sections/ExploreData/MapLevel.js, src/components/toolbars/ExploreDataToolbar/ExploreDataToolbar.js
Fixes #1054
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1054-MakCountyOffshoreMoreVisible/explore/)
- moves state/county and offshore controls down into map
- add MapLevel component to manage map level controls
-
=> Make state, county and offshore controls more visible

src/components/sections/ExploreData/Revenue/RevenueLocationTotal.js
Fixes #1040 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1040-RevenueLocationTotalSpacing
Fixed spacing in revenue explore data page
-
-
-
=> Fixed space issue in revenue location total

src/pages/how-revenue-works/native-american-economic-impact.mdx, src/pages/how-revenue-works/native-american-ownership-governance.mdx, src/pages/how-revenue-works/native-american-production.mdx, src/pages/how-revenue-works/native-american-revenue.mdx
Partial fix for #1203
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Fix-capitalization/how-revenue-works#how-are-natural-resources-on-native-american-land-governed)
- Fix H1 capitalization on all How Revenue Works, Native American pages
=> Change H1s to title case Native American pages

src/components/content-partials/Redirects.mdx
Fixes #1195
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1195-ArchiveRedirect/)
- adds redirect from /archive to https://archive.revenuedata.doi.gov/
-
-
=> add redirect of archive to archive.revenuedata.doi.gov

src/components/info/SnapshotBanner/SnapshotBanner.js, src/pages/fact-sheet.mdx
Fixes #1392
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1392-update-fact-sheet/)
- Update header with a link to revenuedata.doi.gov
- Remove date in header
- Add space between product and units in the production graphs
=> update link, no date and space in prod header

src/pages/downloads/federal-revenue-by-company.mdx, src/pages/downloads/revenue.mdx
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/update-oil&gas-label/)
- on revenue download page change to Oil & gas (pre-production)
- on revenue by company change to Oil & gas since we didn't implement that change in the database yet for that file.
-
=> change label

.env.dev, src/components/data-viz/ProductionLastTwelveMonths/ProductionLastTwelveMonths.js, src/components/data-viz/RevenueLastTwelveMonths/RevenueLastTwelveMonths.js, src/components/sections/TotalDisbursements/TotalDisbursements.js, src/components/sections/TotalProduction/TotalProduction.js, src/components/sections/TotalRevenue/TotalRevenue.js
Fixes #921, #629
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/921-FixCapitalization/)
Commodity and product have regexp to change to first char upper the rest lower
Change units on Geothermal
- @mojo why is this commodity displaying in the drop-down if there was no production nationwide for the whole range of years? _negative number or zero.    I think this falls under different issue_
-
-
-
=> Create for data review PR

src/components/data-viz/RevenueLastTwelveMonths/RevenueLastTwelveMonths.js
Fixes #1495
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/1495-fix-monthly-snap/fact-sheet)
- Columns align in Revenue section with header
-
-
=> removed extra column in header for revenue

database/changelog/changelog-functions/disbursement-functions-refactor.yaml, database/changelog/changelog-functions/production-fy-refactor-functions.yaml, database/changelog/changelog-functions/production-refactor-functions.yaml, database/changelog/changelog-functions/revenue-functions-refactor.yaml, database/changelog/changelog-procedures/disbursement-refactor-procedures.yaml, database/changelog/changelog-procedures/revenue-procedures-refactor.yaml, src/components/data-viz/StackedBarChart/D3StackedBarChart.js, src/components/data-viz/svg/Rect.js
Fixes #2729
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2729-colored-squares/)
- Adds `aria-hidden` attribute to `svg` elements for colored squares
=> Sets aria-hidden for colored squares

src/components/seo.js
Fixes #2978
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2978-remove-dap-tag/)
- Removes redundant google analytics script tag
=> 2978: Removes redundant GA script

src/components/seo.js
Fixes #2978 
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2978-remove-dap-tag/)
- Removes redundant GA script tag
=> 2978: Removes redundant GA script (#3100)
